admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

